server:
  port: 8010

spring:
  application:
    name: microservice-consumer-movie
eureka:
  instance:
    prefer-ip-address: true #true：将自己的ip注册到Eureka Server，false或者不配置：注册微服务所在的操作系统的hostname到Eureka Server
    lease-renewal-interval-in-seconds: 5 #心跳检测间隔时间，默认30秒，开发时配置，生产环境不动
    lease-expiration-duration-in-seconds: 10 #检测异常移除服务时间，默认90秒，开发时配置，生产环境不动
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #Eureka Server的交互地址，注册和发现都需要用它-单点

logging:
  level:
    com.itmuch.cloud.study.user.feign.UserFeignClient: DEBUG #它只支持DEBUG
